---格式化代码实用工具
---@class Text 
---@field Black  
---@field DarkBlue  
---@field DarkGreen  
---@field DarkAqua  
---@field DarkRed  
---@field DarkPurple  
---@field Gold  
---@field Gray  
---@field DarkGray  
---@field Blue  
---@field Green  
---@field Aqua  
---@field Red  
---@field LightPurple  
---@field Yellow  
---@field White  
---@field MinecoinGold   
---@field Bold  
---@field Italics  
---@field Underline  
---@field StrikeThrough  
---@field Random  
---@field Clear  
 Text = {}